# Generated by Django 4.2.6 on 2023-11-24 15:19

from django.db import migrations, models
import django.db.models.deletion
import kumbio_api_v2.communications.models.notifications
import kumbio_api_v2.communications.models.templates


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("appointments", "0002_appointment_hour_end_appointment_hour_init"),
        ("organizations", "0017_remove_professional_is_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (kumbio_api_v2.communications.models.templates.MessageChannel["EMAIL"], 1),
                            (kumbio_api_v2.communications.models.templates.MessageChannel["SMS"], 2),
                            (kumbio_api_v2.communications.models.templates.MessageChannel["WHATSAPP"], 3),
                        ]
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "-modified"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (kumbio_api_v2.communications.models.notifications.MessageType["NOTIFICATION"], 1),
                            (kumbio_api_v2.communications.models.notifications.MessageType["REMINDER"], 2),
                            (kumbio_api_v2.communications.models.notifications.MessageType["ADMINS"], 3),
                        ]
                    ),
                ),
                ("sent", models.BooleanField(default=False)),
                ("send_date", models.DateTimeField(blank=True, null=True)),
                ("sent_date", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("data", models.JSONField(blank=True, null=True)),
                (
                    "appoinment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_notifications",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_notifications",
                        to="organizations.organization",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_notifications",
                        to="communications.mailtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ("-created",),
            },
        ),
    ]
