# Generated by Django 4.2.6 on 2023-12-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0002_alter_mailtemplate_type_alter_notification_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailtemplate",
            name="slug_name",
            field=models.SlugField(default="binevenida", max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
