# Generated by Django 4.2.6 on 2023-12-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0003_mailtemplate_slug_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailtemplate",
            options={},
        ),
        migrations.AlterField(
            model_name="mailtemplate",
            name="subject",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="mailtemplate",
            constraint=models.CheckConstraint(
                check=models.Q(("subject", ""), ("type", 1), _negated=True), name="email_subject_not_empty"
            ),
        ),
    ]
