# Generated by Django 4.2.6 on 2023-12-04 21:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("communications", "0004_alter_mailtemplate_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueueMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("id_message", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: +999999999. Up to 15 digits allowed.",
                                regex="\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("date_sent", models.DateTimeField(blank=True, null=True, verbose_name="Date sent")),
                (
                    "sent",
                    models.BooleanField(
                        default=False, help_text="Set true when message is send.", verbose_name="was sent?"
                    ),
                ),
                ("issue_sent", models.BooleanField(default=False)),
                (
                    "message_type",
                    models.CharField(
                        choices=[("WELCOME", "Welcome Message"), ("REMINDER", "Reminder message"), ("OTHER", "Other")],
                        default="OTHER",
                        max_length=55,
                    ),
                ),
                ("notification_official", models.TextField(blank=True, null=True)),
                ("extra", models.JSONField(blank=True, null=True)),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="queues",
                        to="communications.mailtemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "-modified"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
    ]
