# Generated by Django 4.2.6 on 2023-10-13 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0002_organization_organizationmembership"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sede",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "sede_type",
                    models.CharField(
                        choices=[("PHYSICAL", "Física"), ("VIRTUAL", "Virtual"), ("DOMICILE", "Domicilio")],
                        default="PHYSICAL",
                        max_length=10,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("maps_url", models.URLField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_sedes",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sede",
                "verbose_name_plural": "Sedes",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("duration", models.IntegerField(default=0)),
                ("price", models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ("description", models.TextField(blank=True, null=True)),
                ("sedes", models.ManyToManyField(related_name="sede_services", to="organizations.sede")),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
        migrations.CreateModel(
            name="Professional",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("is_user", models.BooleanField(default=False)),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_professionals",
                        to="organizations.sede",
                    ),
                ),
                ("services", models.ManyToManyField(related_name="service_professionals", to="organizations.service")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Professional",
                "verbose_name_plural": "Professionals",
            },
        ),
    ]
