# Generated by Django 4.2.6 on 2023-10-22 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_sede_service_professional"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubSector",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug_name", models.SlugField(max_length=100, unique=True)),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_sectors",
                        to="organizations.sector",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub Sector",
                "verbose_name_plural": "Sub Sectores",
            },
        ),
    ]
