# Generated by Django 4.2.6 on 2023-10-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0004_subsector"),
    ]

    operations = [
        migrations.AddField(
            model_name="sede",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sede",
            name="phone_aux",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="subsector",
            name="slug_name",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
