# Generated by Django 4.2.6 on 2023-10-23 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0005_sede_description_sede_phone_aux_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeadquarterSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("MONDAY", "Lunes"),
                            ("TUESDAY", "Martes"),
                            ("WEDNESDAY", "Miércoles"),
                            ("THURSDAY", "Jueves"),
                            ("FRIDAY", "Viernes"),
                            ("SATURDAY", "Sábado"),
                            ("SUNDAY", "Domingo"),
                        ],
                        default="MONDAY",
                        max_length=10,
                    ),
                ),
                ("hour_init", models.TimeField()),
                ("hour_end", models.TimeField()),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sede_schedule",
                        to="organizations.sede",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horario de la sede",
                "verbose_name_plural": "Horarios de las sedes",
            },
        ),
    ]
