# Generated by Django 4.2.6 on 2023-10-23 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0007_professionalschedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug_name", models.SlugField(max_length=255)),
                ("phone_prefix", models.CharField(max_length=255)),
                ("alpha_code", models.CharField(max_length=255)),
                ("alpha_code1", models.CharField(max_length=255)),
                ("timezone_raw", models.CharField(blank=True, max_length=255, null=True)),
                ("minutes_diff", models.IntegerField(default=0)),
                ("max_length_phone", models.IntegerField(blank=True, null=True)),
                ("min_length_phone", models.IntegerField(blank=True, null=True)),
                (
                    "optional_prefix",
                    models.CharField(
                        blank=True,
                        help_text="Some countries as Mexico or Argentina has a prefix number that is located in the middle of the country code and the number",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Países",
            },
        ),
        migrations.AlterField(
            model_name="organization",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_country",
                to="organizations.country",
            ),
        ),
    ]
