# Generated by Django 4.2.6 on 2023-10-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0008_country_alter_organization_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="optional_prefix",
            field=models.CharField(blank=True, help_text="Some countries prefix", max_length=255, null=True),
        ),
    ]
