# Generated by Django 4.2.6 on 2023-10-31 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0008_country_alter_organization_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="sector",
        ),
        migrations.AddField(
            model_name="organization",
            name="sub_sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_sectors",
                to="organizations.subsector",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="optional_prefix",
            field=models.CharField(blank=True, help_text="Some countries prefix", max_length=255, null=True),
        ),
    ]
