# Generated by Django 4.2.6 on 2023-11-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0011_organization_how_you_know_us_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="professional",
            name="description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
