# Generated by Django 4.2.6 on 2023-11-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0012_professional_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmembership",
            name="days_duration",
            field=models.IntegerField(default=30),
        ),
    ]
