# Generated by Django 4.2.6 on 2023-11-03 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0013_organizationmembership_days_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestProfessionalSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("MONDAY", "Lunes"),
                            ("TUESDAY", "Martes"),
                            ("WEDNESDAY", "Miércoles"),
                            ("THURSDAY", "Jueves"),
                            ("FRIDAY", "Viernes"),
                            ("SATURDAY", "Sábado"),
                            ("SUNDAY", "Domingo"),
                        ],
                        default="MONDAY",
                        max_length=10,
                    ),
                ),
                ("hour_init", models.TimeField()),
                ("hour_end", models.TimeField()),
                (
                    "professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rest_professional_schedule",
                        to="organizations.professional",
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "-modified"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
    ]
