# Generated by Django 4.2.6 on 2023-11-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0014_restprofessionalschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="restprofessionalschedule",
            name="description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="restprofessionalschedule",
            name="on_vacations",
            field=models.BooleanField(default=False),
        ),
    ]
