# Generated by Django 4.2.6 on 2023-11-14 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0015_restprofessionalschedule_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restprofessionalschedule",
            name="day",
        ),
        migrations.RemoveField(
            model_name="restprofessionalschedule",
            name="hour_end",
        ),
        migrations.RemoveField(
            model_name="restprofessionalschedule",
            name="hour_init",
        ),
        migrations.RemoveField(
            model_name="restprofessionalschedule",
            name="on_vacations",
        ),
        migrations.AddField(
            model_name="professionalschedule",
            name="hour_end_rest",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="professionalschedule",
            name="hour_init_rest",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restprofessionalschedule",
            name="date_end",
            field=models.DateField(default=datetime.date(2023, 11, 14)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restprofessionalschedule",
            name="date_init",
            field=models.DateField(default=datetime.date(2023, 11, 14)),
            preserve_default=False,
        ),
    ]
