# Generated by Django 4.2.6 on 2023-11-17 04:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0016_remove_restprofessionalschedule_day_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professional",
            name="is_user",
        ),
    ]
