# Generated by Django 4.2.6 on 2023-12-11 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0020_organization_onboarding_state_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="professionalschedule",
            options={"verbose_name": "Professional Schedule", "verbose_name_plural": "Professional Schedules"},
        ),
        migrations.AlterModelOptions(
            name="restprofessionalschedule",
            options={
                "verbose_name": "Rest Professional Schedule",
                "verbose_name_plural": "Rest Professional Schedules",
            },
        ),
        migrations.AddField(
            model_name="headquarterschedule",
            name="is_working",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="headquarterschedule",
            name="note",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="professionalschedule",
            name="is_working",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="professionalschedule",
            name="note",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="professional",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="professional", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="headquarterschedule",
            unique_together={("sede", "day", "hour_init"), ("sede", "day", "hour_end")},
        ),
        migrations.AlterUniqueTogether(
            name="professionalschedule",
            unique_together={("professional", "day", "hour_end"), ("professional", "day", "hour_init")},
        ),
        migrations.AlterUniqueTogether(
            name="restprofessionalschedule",
            unique_together={("professional", "date_init"), ("professional", "date_end")},
        ),
        migrations.RemoveField(
            model_name="professionalschedule",
            name="hour_end_rest",
        ),
        migrations.RemoveField(
            model_name="professionalschedule",
            name="hour_init_rest",
        ),
    ]
