# Generated by Django 4.2.6 on 2023-12-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0022_alter_service_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="automatic_reminder",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name="email address"),
        ),
        migrations.AddField(
            model_name="organization",
            name="language",
            field=models.CharField(choices=[("SPANISH", "Español"), ("ENGLISH", "Inglés")], default="SPANISH"),
        ),
        migrations.AddField(
            model_name="organization",
            name="minimun_days_reserve",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="organization",
            name="phone_number",
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="web_site",
            field=models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name="Link sitio web"),
        ),
    ]
