# Generated by Django 4.2.6 on 2023-12-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0022_alter_service_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="duration",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="service",
            name="duration",
            field=models.PositiveIntegerField(),
        ),
    ]
