# Generated by Django 4.2.6 on 2023-12-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0023_organization_automatic_reminder_organization_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="terms_and_conditions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
