# Generated by Django 4.2.6 on 2023-12-12 23:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0023_alter_service_duration"),
        ("organizations", "0024_service_terms_and_conditions"),
    ]

    operations = []
