# Generated by Django 4.2.6 on 2023-12-27 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0025_merge_20231212_2324"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="restprofessionalschedule",
            unique_together=set(),
        ),
    ]
