# Generated by Django 4.2.6 on 2023-10-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_first_name_user_last_name_user_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_client",
            field=models.BooleanField(
                default=False, help_text="Indica si el usuario es cliente", verbose_name="Cliente"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_owner",
            field=models.BooleanField(
                default=False, help_text="Indica si el usuario es propietario", verbose_name="Owner"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_professional",
            field=models.BooleanField(
                default=False, help_text="Indica si el usuario es profesional", verbose_name="Profesional"
            ),
        ),
    ]
