# Generated by Django 4.2.6 on 2023-11-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_is_client_user_is_owner_user_is_professional"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_administrator",
            field=models.BooleanField(
                default=False, help_text="Indica si el usuario es administrador", verbose_name="Admin"
            ),
        ),
    ]
