# Generated by Django 4.2.6 on 2023-11-21 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_is_administrator"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("photo", models.FileField(blank=True, null=True, upload_to="users/photos")),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CEDULA", "Cédula de ciudadanía"),
                            ("TI", "Tarjeta de identidad"),
                            ("DNI", "Dni"),
                            ("CEDULA_EX", "Cédula de extranjería"),
                            ("PASS", "Pasaporte"),
                        ],
                        default="CEDULA",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("document_number", models.CharField(blank=True, max_length=50, null=True)),
                ("gender_type", models.CharField(blank=True, max_length=255, null=True)),
                ("extra_fields", models.JSONField(blank=True, null=True)),
                ("birthdate", models.DateField(blank=True, null=True)),
                ("phone_number_2", models.CharField(blank=True, max_length=20, null=True)),
                ("emergency_contact", models.CharField(blank=True, max_length=255, null=True)),
                ("observations", models.TextField(blank=True, null=True)),
                (
                    "is_main",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el usuario es el cliente principal",
                        verbose_name="Cliente principal",
                    ),
                ),
                (
                    "is_secondary",
                    models.BooleanField(
                        default=False,
                        help_text="El usuario es el cliente dependiente",
                        verbose_name="Cliente dependiente",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de usuario",
                "verbose_name_plural": "Perfiles de usuarios",
            },
        ),
    ]
