# Generated by Django 4.2.6 on 2023-11-23 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0017_remove_professional_is_user"),
        ("users", "0005_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="organization",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_profile",
                to="organizations.organization",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="is_main",
            field=models.BooleanField(
                default=False, help_text="Es el cliente principal", verbose_name="Cliente principal"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="is_secondary",
            field=models.BooleanField(
                default=False, help_text="Es el cliente dependiente", verbose_name="Cliente dependiente"
            ),
        ),
    ]
