# Generated by Django 4.2.6 on 2023-11-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="hour_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="hour_init",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
