# Generated by Django 4.2.6 on 2023-12-11 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0021_alter_professionalschedule_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("appointments", "0002_appointment_hour_end_appointment_hour_init"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="client_user",
            field=models.ForeignKey(
                limit_choices_to={"is_client": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="created_by_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="professional_user",
            field=models.ForeignKey(
                limit_choices_to={"is_professional": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="professional_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="hour_end",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="hour_init",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="sede",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sede_appointments",
                to="organizations.sede",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_appointments",
                to="organizations.service",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={
                ("client_user", "date", "hour_end"),
                ("professional_user", "date", "hour_init"),
                ("professional_user", "date", "hour_end"),
                ("client_user", "date", "hour_init"),
            },
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="professional",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="start_date",
        ),
    ]
