# Generated by Django 4.2.6 on 2023-12-20 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0025_merge_20231212_2324"),
        ("appointments", "0003_appointment_client_user_appointment_created_by_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DurationSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date time on which the object was created.", verbose_name="created at"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, help_text="Date time on which the object was last modified.", verbose_name="modified at"
                    ),
                ),
                ("hour_init", models.TimeField()),
                ("hour_end", models.TimeField()),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("MONDAY", "Lunes"),
                            ("TUESDAY", "Martes"),
                            ("WEDNESDAY", "Miércoles"),
                            ("THURSDAY", "Jueves"),
                            ("FRIDAY", "Viernes"),
                            ("SATURDAY", "Sábado"),
                            ("SUNDAY", "Domingo"),
                        ],
                        default="MONDAY",
                        max_length=10,
                    ),
                ),
                (
                    "professional_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="durations", to="organizations.professionalschedule"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="durations", to="organizations.service"),
                ),
            ],
            options={
                "verbose_name": "Duración de la cita",
                "verbose_name_plural": "Duraciones de las citas",
                "unique_together": {
                    ("professional_schedule", "service", "day", "hour_init"),
                    ("professional_schedule", "service", "day", "hour_end"),
                },
            },
        ),
    ]
