# Generated by Django 4.2.6 on 2023-12-27 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0004_durationschedule"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name="DurationSchedule",
        ),
    ]
