# Generated by Django 4.2.6 on 2023-12-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0005_alter_appointment_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="appointment_status",
            field=models.CharField(
                choices=[("PENDING", "Pendiente"), ("COMPLETED", "COMPLETED"), ("CANCELED", "Cancelado")],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
