# Generated by Django 4.2.6 on 2023-12-28 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0026_alter_restprofessionalschedule_unique_together"),
        ("appointments", "0006_appointment_appointment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="professional_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="professional_appointments",
                to="organizations.professional",
            ),
        ),
    ]
